#build_xtensa:
#	west build -b qemu_xtensa ../system_base/
#
#simulate_xtensa:
#	west build -t run

build_riscv:
	west build -b qemu_riscv32e ../system_base/

simulate_riscv:
	west build -t run

clean:
	rm -rf ./build
